// <auto-generated />
using System;
using CarPark.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarPark.Infrastructure.Migrations
{
    [DbContext(typeof(CarParkDbContext))]
    [Migration("20250919053252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPark.Domain.Entities.ParkingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("VehicleCharge")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ParkingRecords");
                });

            modelBuilder.Entity("CarPark.Domain.Entities.ParkingSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            SpaceNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            SpaceNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            SpaceNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            SpaceNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            SpaceNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            SpaceNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            SpaceNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            SpaceNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            SpaceNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            SpaceNumber = 10
                        },
                        new
                        {
                            Id = 11,
                            IsOccupied = false,
                            SpaceNumber = 11
                        },
                        new
                        {
                            Id = 12,
                            IsOccupied = false,
                            SpaceNumber = 12
                        },
                        new
                        {
                            Id = 13,
                            IsOccupied = false,
                            SpaceNumber = 13
                        },
                        new
                        {
                            Id = 14,
                            IsOccupied = false,
                            SpaceNumber = 14
                        },
                        new
                        {
                            Id = 15,
                            IsOccupied = false,
                            SpaceNumber = 15
                        },
                        new
                        {
                            Id = 16,
                            IsOccupied = false,
                            SpaceNumber = 16
                        },
                        new
                        {
                            Id = 17,
                            IsOccupied = false,
                            SpaceNumber = 17
                        },
                        new
                        {
                            Id = 18,
                            IsOccupied = false,
                            SpaceNumber = 18
                        },
                        new
                        {
                            Id = 19,
                            IsOccupied = false,
                            SpaceNumber = 19
                        },
                        new
                        {
                            Id = 20,
                            IsOccupied = false,
                            SpaceNumber = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
